#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrollment_System_2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ENROLLMENT_DB")]
	public partial class enrollmentDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public enrollmentDataContext() : 
				base(global::Enrollment_System_2.Properties.Settings.Default.ENROLLMENT_DBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public enrollmentDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public enrollmentDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public enrollmentDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public enrollmentDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ad_delete")]
		public int ad_delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ad_login")]
		public ISingleResult<ad_loginResult> ad_login([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Admin_Username", DbType="VarChar(50)")] string admin_Username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Admin_Pass", DbType="VarChar(50)")] string admin_Pass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), admin_Username, admin_Pass);
			return ((ISingleResult<ad_loginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ad_save")]
		public int ad_save([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fname", DbType="VarChar(50)")] string fname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lname", DbType="VarChar(50)")] string lname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mname", DbType="VarChar(50)")] string mname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Phonenum", DbType="Char(11)")] string phonenum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="VarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pass", DbType="VarChar(50)")] string pass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fname, lname, mname, phonenum, username, pass);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ad_search")]
		public ISingleResult<ad_searchResult> ad_search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key);
			return ((ISingleResult<ad_searchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ad_update")]
		public int ad_update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fname", DbType="VarChar(50)")] string fname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lname", DbType="VarChar(50)")] string lname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mname", DbType="VarChar(50)")] string mname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Phonenum", DbType="Char(11)")] string phonenum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="VarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pass", DbType="VarChar(50)")] string pass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, fname, lname, mname, phonenum, username, pass);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ad_view")]
		public ISingleResult<ad_viewResult> ad_view()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ad_viewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cls_delete")]
		public int cls_delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MIS_CODE", DbType="VarChar(50)")] string mIS_CODE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mIS_CODE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cls_save")]
		public int cls_save([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MIS_CODE", DbType="VarChar(50)")] string mIS_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLASS_TIME", DbType="VarChar(100)")] string cLASS_TIME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLASS_DAY", DbType="VarChar(10)")] string cLASS_DAY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLASS_SHIFT", DbType="VarChar(10)")] string cLASS_SHIFT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLASS_ROOM", DbType="VarChar(10)")] string cLASS_ROOM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SECTION", DbType="VarChar(3)")] string sECTION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUB_CODE", DbType="VarChar(25)")] string sUB_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROF_ID", DbType="Int")] System.Nullable<int> pROF_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mIS_CODE, cLASS_TIME, cLASS_DAY, cLASS_SHIFT, cLASS_ROOM, sECTION, sUB_CODE, pROF_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cls_search")]
		public ISingleResult<cls_searchResult> cls_search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key);
			return ((ISingleResult<cls_searchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cls_update")]
		public int cls_update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MIS_CODE", DbType="VarChar(50)")] string mIS_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLASS_TIME", DbType="VarChar(100)")] string cLASS_TIME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLASS_DAY", DbType="VarChar(10)")] string cLASS_DAY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLASS_SHIFT", DbType="VarChar(10)")] string cLASS_SHIFT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLASS_ROOM", DbType="VarChar(10)")] string cLASS_ROOM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SECTION", DbType="VarChar(3)")] string sECTION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUB_CODE", DbType="VarChar(25)")] string sUB_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROF_ID", DbType="Int")] System.Nullable<int> pROF_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mIS_CODE, cLASS_TIME, cLASS_DAY, cLASS_SHIFT, cLASS_ROOM, sECTION, sUB_CODE, pROF_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cls_view")]
		public ISingleResult<cls_viewResult> cls_view()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cls_viewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.enr_delete")]
		public int enr_delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MIS_CODE", DbType="VarChar(50)")] string mIS_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mIS_CODE, iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.enr_save")]
		public int enr_save([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MIS_CODE", DbType="VarChar(50)")] string mIS_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STAT", DbType="VarChar(15)")] string sTAT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ENROLL_DATE", DbType="Date")] System.Nullable<System.DateTime> eNROLL_DATE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mIS_CODE, iD, sTAT, eNROLL_DATE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.enr_search")]
		public ISingleResult<enr_searchResult> enr_search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key);
			return ((ISingleResult<enr_searchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.enr_update")]
		public int enr_update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MIS_CODE", DbType="VarChar(50)")] string mIS_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STAT", DbType="VarChar(15)")] string sTAT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mIS_CODE, iD, sTAT);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.enr_view")]
		public ISingleResult<enr_viewResult> enr_view()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<enr_viewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.enrollees")]
		public ISingleResult<enrolleesResult> enrollees()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<enrolleesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.prof_delete")]
		public int prof_delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROF_ID", DbType="Int")] System.Nullable<int> pROF_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pROF_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.prof_save")]
		public int prof_save([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROF_FNAME", DbType="VarChar(60)")] string pROF_FNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROF_LNAME", DbType="VarChar(60)")] string pROF_LNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROF_MIDNAME", DbType="VarChar(60)")] string pROF_MIDNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROF_CONTACT", DbType="Char(11)")] string pROF_CONTACT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROF_BIRTHDATE", DbType="Date")] System.Nullable<System.DateTime> pROF_BIRTHDATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROF_ADDRESS", DbType="VarChar(100)")] string pROF_ADDRESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROF_EMAIL", DbType="VarChar(60)")] string pROF_EMAIL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROF_AGE", DbType="SmallInt")] System.Nullable<short> pROF_AGE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DATE_CREATE", DbType="DateTime")] System.Nullable<System.DateTime> dATE_CREATE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pROF_FNAME, pROF_LNAME, pROF_MIDNAME, pROF_CONTACT, pROF_BIRTHDATE, pROF_ADDRESS, pROF_EMAIL, pROF_AGE, dATE_CREATE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.prof_search")]
		public ISingleResult<prof_searchResult> prof_search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key);
			return ((ISingleResult<prof_searchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.prof_update")]
		public int prof_update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROF_ID", DbType="Int")] System.Nullable<int> pROF_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROF_FNAME", DbType="VarChar(60)")] string pROF_FNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROF_LNAME", DbType="VarChar(60)")] string pROF_LNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROF_MIDNAME", DbType="VarChar(60)")] string pROF_MIDNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROF_CONTACT", DbType="Char(11)")] string pROF_CONTACT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROF_BIRTHDATE", DbType="Date")] System.Nullable<System.DateTime> pROF_BIRTHDATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROF_ADDRESS", DbType="VarChar(100)")] string pROF_ADDRESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROF_EMAIL", DbType="VarChar(60)")] string pROF_EMAIL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROF_AGE", DbType="SmallInt")] System.Nullable<short> pROF_AGE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pROF_ID, pROF_FNAME, pROF_LNAME, pROF_MIDNAME, pROF_CONTACT, pROF_BIRTHDATE, pROF_ADDRESS, pROF_EMAIL, pROF_AGE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.prof_view")]
		public ISingleResult<prof_viewResult> prof_view()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<prof_viewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.prog_delete")]
		public int prog_delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROG_ID", DbType="Int")] System.Nullable<int> pROG_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pROG_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.prog_save")]
		public int prog_save([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROG_DESC", DbType="VarChar(100)")] string pROG_DESC)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pROG_DESC);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.prog_search")]
		public ISingleResult<prog_searchResult> prog_search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key);
			return ((ISingleResult<prog_searchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.prog_update")]
		public int prog_update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROG_ID", DbType="Int")] System.Nullable<int> pROG_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROG_DESC", DbType="VarChar(100)")] string pROG_DESC)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pROG_ID, pROG_DESC);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.prog_view")]
		public ISingleResult<prog_viewResult> prog_view()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<prog_viewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.search_enrollees")]
		public ISingleResult<search_enrolleesResult> search_enrollees([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key);
			return ((ISingleResult<search_enrolleesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stud_delete")]
		public int stud_delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_ID", DbType="Int")] System.Nullable<int> sTUD_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTUD_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stud_save")]
		public int stud_save([global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_FNAME", DbType="VarChar(60)")] string sTUD_FNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_LNAME", DbType="VarChar(60)")] string sTUD_LNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_MIDNAME", DbType="VarChar(60)")] string sTUD_MIDNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_GENDER", DbType="VarChar(10)")] string sTUD_GENDER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_CONTACT", DbType="Char(11)")] string sTUD_CONTACT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_BIRTHDATE", DbType="Date")] System.Nullable<System.DateTime> sTUD_BIRTHDATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_AGE", DbType="SmallInt")] System.Nullable<short> sTUD_AGE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_ADDRESS", DbType="VarChar(100)")] string sTUD_ADDRESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_EMAIL", DbType="VarChar(60)")] string sTUD_EMAIL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="YEAR_LEVEL", DbType="VarChar(15)")] string yEAR_LEVEL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_STATUS", DbType="VarChar(20)")] string sTUD_STATUS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DATE_CREATE", DbType="DateTime")] System.Nullable<System.DateTime> dATE_CREATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROGRAM_ID", DbType="Int")] System.Nullable<int> pROGRAM_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTUD_FNAME, sTUD_LNAME, sTUD_MIDNAME, sTUD_GENDER, sTUD_CONTACT, sTUD_BIRTHDATE, sTUD_AGE, sTUD_ADDRESS, sTUD_EMAIL, yEAR_LEVEL, sTUD_STATUS, dATE_CREATE, pROGRAM_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stud_search")]
		public ISingleResult<stud_searchResult> stud_search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key);
			return ((ISingleResult<stud_searchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stud_update")]
		public int stud_update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_ID", DbType="Int")] System.Nullable<int> sTUD_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_FNAME", DbType="VarChar(60)")] string sTUD_FNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_LNAME", DbType="VarChar(60)")] string sTUD_LNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_MIDNAME", DbType="VarChar(60)")] string sTUD_MIDNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_GENDER", DbType="VarChar(10)")] string sTUD_GENDER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_CONTACT", DbType="Char(11)")] string sTUD_CONTACT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_BIRTHDATE", DbType="Date")] System.Nullable<System.DateTime> sTUD_BIRTHDATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_AGE", DbType="SmallInt")] System.Nullable<short> sTUD_AGE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_ADDRESS", DbType="VarChar(100)")] string sTUD_ADDRESS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_EMAIL", DbType="VarChar(60)")] string sTUD_EMAIL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="YEAR_LEVEL", DbType="VarChar(15)")] string yEAR_LEVEL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUD_STAT", DbType="VarChar(20)")] string sTUD_STAT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROGRAM_ID", DbType="Int")] System.Nullable<int> pROGRAM_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTUD_ID, sTUD_FNAME, sTUD_LNAME, sTUD_MIDNAME, sTUD_GENDER, sTUD_CONTACT, sTUD_BIRTHDATE, sTUD_AGE, sTUD_ADDRESS, sTUD_EMAIL, yEAR_LEVEL, sTUD_STAT, pROGRAM_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stud_view")]
		public ISingleResult<stud_viewResult> stud_view()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<stud_viewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sub_delete")]
		public int sub_delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUB_CODE", DbType="VarChar(25)")] string sUB_CODE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sUB_CODE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sub_save")]
		public int sub_save([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUB_CODE", DbType="VarChar(25)")] string sUB_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUB_DESCRIPTION", DbType="VarChar(100)")] string sUB_DESCRIPTION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUB_YEAR", DbType="VarChar(15)")] string sUB_YEAR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUB_SEM", DbType="VarChar(30)")] string sUB_SEM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UNIT", DbType="Decimal(10,2)")] System.Nullable<decimal> uNIT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sUB_CODE, sUB_DESCRIPTION, sUB_YEAR, sUB_SEM, uNIT);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sub_search")]
		public ISingleResult<sub_searchResult> sub_search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key);
			return ((ISingleResult<sub_searchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sub_update")]
		public int sub_update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUB_CODE", DbType="VarChar(25)")] string sUB_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUB_DESCRIPTION", DbType="VarChar(100)")] string sUB_DESCRIPTION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUB_YEAR", DbType="VarChar(15)")] string sUB_YEAR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUB_SEM", DbType="VarChar(30)")] string sUB_SEM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UNIT", DbType="Decimal(10,2)")] System.Nullable<decimal> uNIT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sUB_CODE, sUB_DESCRIPTION, sUB_YEAR, sUB_SEM, uNIT);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sub_view")]
		public ISingleResult<sub_viewResult> sub_view()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sub_viewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.select_Userdetail")]
		public ISingleResult<select_UserdetailResult> select_Userdetail([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<select_UserdetailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.selectId")]
		public ISingleResult<selectIdResult> selectId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Admin_Username", DbType="VarChar(50)")] string admin_Username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Admin_Pass", DbType="VarChar(50)")] string admin_Pass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), admin_Username, admin_Pass);
			return ((ISingleResult<selectIdResult>)(result.ReturnValue));
		}
	}
	
	public partial class ad_loginResult
	{
		
		private int _id;
		
		private string _Admin_Fname;
		
		private string _Admin_Lname;
		
		private string _Admin_Midname;
		
		private string _Admin_Contact;
		
		private string _Admin_Username;
		
		private string _Admin_Pass;
		
		public ad_loginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Fname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Admin_Fname
		{
			get
			{
				return this._Admin_Fname;
			}
			set
			{
				if ((this._Admin_Fname != value))
				{
					this._Admin_Fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Lname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Admin_Lname
		{
			get
			{
				return this._Admin_Lname;
			}
			set
			{
				if ((this._Admin_Lname != value))
				{
					this._Admin_Lname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Midname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Admin_Midname
		{
			get
			{
				return this._Admin_Midname;
			}
			set
			{
				if ((this._Admin_Midname != value))
				{
					this._Admin_Midname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Contact", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string Admin_Contact
		{
			get
			{
				return this._Admin_Contact;
			}
			set
			{
				if ((this._Admin_Contact != value))
				{
					this._Admin_Contact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Admin_Username
		{
			get
			{
				return this._Admin_Username;
			}
			set
			{
				if ((this._Admin_Username != value))
				{
					this._Admin_Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Pass", DbType="VarChar(50)")]
		public string Admin_Pass
		{
			get
			{
				return this._Admin_Pass;
			}
			set
			{
				if ((this._Admin_Pass != value))
				{
					this._Admin_Pass = value;
				}
			}
		}
	}
	
	public partial class ad_searchResult
	{
		
		private string _Admin_Fname;
		
		private string _Admin_Lname;
		
		private string _Admin_Midname;
		
		private string _Admin_Contact;
		
		public ad_searchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Fname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Admin_Fname
		{
			get
			{
				return this._Admin_Fname;
			}
			set
			{
				if ((this._Admin_Fname != value))
				{
					this._Admin_Fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Lname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Admin_Lname
		{
			get
			{
				return this._Admin_Lname;
			}
			set
			{
				if ((this._Admin_Lname != value))
				{
					this._Admin_Lname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Midname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Admin_Midname
		{
			get
			{
				return this._Admin_Midname;
			}
			set
			{
				if ((this._Admin_Midname != value))
				{
					this._Admin_Midname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Contact", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string Admin_Contact
		{
			get
			{
				return this._Admin_Contact;
			}
			set
			{
				if ((this._Admin_Contact != value))
				{
					this._Admin_Contact = value;
				}
			}
		}
	}
	
	public partial class ad_viewResult
	{
		
		private int _id;
		
		private string _Admin_Fname;
		
		private string _Admin_Lname;
		
		private string _Admin_Midname;
		
		private string _Admin_Contact;
		
		private string _Admin_Username;
		
		private string _Admin_Pass;
		
		public ad_viewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Fname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Admin_Fname
		{
			get
			{
				return this._Admin_Fname;
			}
			set
			{
				if ((this._Admin_Fname != value))
				{
					this._Admin_Fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Lname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Admin_Lname
		{
			get
			{
				return this._Admin_Lname;
			}
			set
			{
				if ((this._Admin_Lname != value))
				{
					this._Admin_Lname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Midname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Admin_Midname
		{
			get
			{
				return this._Admin_Midname;
			}
			set
			{
				if ((this._Admin_Midname != value))
				{
					this._Admin_Midname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Contact", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string Admin_Contact
		{
			get
			{
				return this._Admin_Contact;
			}
			set
			{
				if ((this._Admin_Contact != value))
				{
					this._Admin_Contact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Admin_Username
		{
			get
			{
				return this._Admin_Username;
			}
			set
			{
				if ((this._Admin_Username != value))
				{
					this._Admin_Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Pass", DbType="VarChar(50)")]
		public string Admin_Pass
		{
			get
			{
				return this._Admin_Pass;
			}
			set
			{
				if ((this._Admin_Pass != value))
				{
					this._Admin_Pass = value;
				}
			}
		}
	}
	
	public partial class cls_searchResult
	{
		
		private string _MIS_CODE;
		
		private string _COURSE_CODE;
		
		private string _YEAR;
		
		private string _SECTION;
		
		private string _TIME;
		
		private string _CLASS_DAYS;
		
		private string _SHIFT;
		
		private string _ROOM;
		
		private System.Nullable<int> _PROF_ID;
		
		private string _PROFESSOR;
		
		public cls_searchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MIS CODE]", Storage="_MIS_CODE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MIS_CODE
		{
			get
			{
				return this._MIS_CODE;
			}
			set
			{
				if ((this._MIS_CODE != value))
				{
					this._MIS_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[COURSE CODE]", Storage="_COURSE_CODE", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string COURSE_CODE
		{
			get
			{
				return this._COURSE_CODE;
			}
			set
			{
				if ((this._COURSE_CODE != value))
				{
					this._COURSE_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string YEAR
		{
			get
			{
				return this._YEAR;
			}
			set
			{
				if ((this._YEAR != value))
				{
					this._YEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECTION", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string SECTION
		{
			get
			{
				return this._SECTION;
			}
			set
			{
				if ((this._SECTION != value))
				{
					this._SECTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string TIME
		{
			get
			{
				return this._TIME;
			}
			set
			{
				if ((this._TIME != value))
				{
					this._TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CLASS DAYS]", Storage="_CLASS_DAYS", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string CLASS_DAYS
		{
			get
			{
				return this._CLASS_DAYS;
			}
			set
			{
				if ((this._CLASS_DAYS != value))
				{
					this._CLASS_DAYS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHIFT", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SHIFT
		{
			get
			{
				return this._SHIFT;
			}
			set
			{
				if ((this._SHIFT != value))
				{
					this._SHIFT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM", DbType="VarChar(10)")]
		public string ROOM
		{
			get
			{
				return this._ROOM;
			}
			set
			{
				if ((this._ROOM != value))
				{
					this._ROOM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROF_ID", DbType="Int")]
		public System.Nullable<int> PROF_ID
		{
			get
			{
				return this._PROF_ID;
			}
			set
			{
				if ((this._PROF_ID != value))
				{
					this._PROF_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROFESSOR", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string PROFESSOR
		{
			get
			{
				return this._PROFESSOR;
			}
			set
			{
				if ((this._PROFESSOR != value))
				{
					this._PROFESSOR = value;
				}
			}
		}
	}
	
	public partial class cls_viewResult
	{
		
		private string _MIS_CODE;
		
		private string _COURSE_CODE;
		
		private string _YEAR;
		
		private string _SECTION;
		
		private string _TIME;
		
		private string _CLASS_DAYS;
		
		private string _SHIFT;
		
		private string _ROOM;
		
		private System.Nullable<int> _PROF_ID;
		
		private string _PROFESSOR;
		
		public cls_viewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MIS CODE]", Storage="_MIS_CODE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MIS_CODE
		{
			get
			{
				return this._MIS_CODE;
			}
			set
			{
				if ((this._MIS_CODE != value))
				{
					this._MIS_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[COURSE CODE]", Storage="_COURSE_CODE", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string COURSE_CODE
		{
			get
			{
				return this._COURSE_CODE;
			}
			set
			{
				if ((this._COURSE_CODE != value))
				{
					this._COURSE_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string YEAR
		{
			get
			{
				return this._YEAR;
			}
			set
			{
				if ((this._YEAR != value))
				{
					this._YEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECTION", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string SECTION
		{
			get
			{
				return this._SECTION;
			}
			set
			{
				if ((this._SECTION != value))
				{
					this._SECTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string TIME
		{
			get
			{
				return this._TIME;
			}
			set
			{
				if ((this._TIME != value))
				{
					this._TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CLASS DAYS]", Storage="_CLASS_DAYS", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string CLASS_DAYS
		{
			get
			{
				return this._CLASS_DAYS;
			}
			set
			{
				if ((this._CLASS_DAYS != value))
				{
					this._CLASS_DAYS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHIFT", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SHIFT
		{
			get
			{
				return this._SHIFT;
			}
			set
			{
				if ((this._SHIFT != value))
				{
					this._SHIFT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM", DbType="VarChar(10)")]
		public string ROOM
		{
			get
			{
				return this._ROOM;
			}
			set
			{
				if ((this._ROOM != value))
				{
					this._ROOM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROF_ID", DbType="Int")]
		public System.Nullable<int> PROF_ID
		{
			get
			{
				return this._PROF_ID;
			}
			set
			{
				if ((this._PROF_ID != value))
				{
					this._PROF_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROFESSOR", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string PROFESSOR
		{
			get
			{
				return this._PROFESSOR;
			}
			set
			{
				if ((this._PROFESSOR != value))
				{
					this._PROFESSOR = value;
				}
			}
		}
	}
	
	public partial class enr_searchResult
	{
		
		private string _MIS_CODE;
		
		private string _STUDENT_ID;
		
		private string _STATUS;
		
		private string _YEAR_LEVEL;
		
		private string _SEMESTER;
		
		public enr_searchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MIS_CODE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MIS_CODE
		{
			get
			{
				return this._MIS_CODE;
			}
			set
			{
				if ((this._MIS_CODE != value))
				{
					this._MIS_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[STUDENT ID]", Storage="_STUDENT_ID", DbType="VarChar(7)")]
		public string STUDENT_ID
		{
			get
			{
				return this._STUDENT_ID;
			}
			set
			{
				if ((this._STUDENT_ID != value))
				{
					this._STUDENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR_LEVEL", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string YEAR_LEVEL
		{
			get
			{
				return this._YEAR_LEVEL;
			}
			set
			{
				if ((this._YEAR_LEVEL != value))
				{
					this._YEAR_LEVEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEMESTER", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string SEMESTER
		{
			get
			{
				return this._SEMESTER;
			}
			set
			{
				if ((this._SEMESTER != value))
				{
					this._SEMESTER = value;
				}
			}
		}
	}
	
	public partial class enr_viewResult
	{
		
		private string _MIS_CODE;
		
		private string _STUDENT_ID;
		
		private string _STATUS;
		
		private string _YEAR_LEVEL;
		
		private string _SEMESTER;
		
		public enr_viewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MIS_CODE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MIS_CODE
		{
			get
			{
				return this._MIS_CODE;
			}
			set
			{
				if ((this._MIS_CODE != value))
				{
					this._MIS_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[STUDENT ID]", Storage="_STUDENT_ID", DbType="VarChar(7)")]
		public string STUDENT_ID
		{
			get
			{
				return this._STUDENT_ID;
			}
			set
			{
				if ((this._STUDENT_ID != value))
				{
					this._STUDENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR_LEVEL", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string YEAR_LEVEL
		{
			get
			{
				return this._YEAR_LEVEL;
			}
			set
			{
				if ((this._YEAR_LEVEL != value))
				{
					this._YEAR_LEVEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEMESTER", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string SEMESTER
		{
			get
			{
				return this._SEMESTER;
			}
			set
			{
				if ((this._SEMESTER != value))
				{
					this._SEMESTER = value;
				}
			}
		}
	}
	
	public partial class enrolleesResult
	{
		
		private int _STUDENT_ID;
		
		private string _FIRSTNAME;
		
		private string _LASTNAME;
		
		private string _MIDDLE_NAME;
		
		private string _YEAR_LEVEL;
		
		private string _STATUS;
		
		private string _PROGRAM;
		
		private string _SHIFT;
		
		private string _SECTION;
		
		private System.DateTime _DATE_ENROLLED;
		
		public enrolleesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[STUDENT ID]", Storage="_STUDENT_ID", DbType="Int NOT NULL")]
		public int STUDENT_ID
		{
			get
			{
				return this._STUDENT_ID;
			}
			set
			{
				if ((this._STUDENT_ID != value))
				{
					this._STUDENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRSTNAME", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string FIRSTNAME
		{
			get
			{
				return this._FIRSTNAME;
			}
			set
			{
				if ((this._FIRSTNAME != value))
				{
					this._FIRSTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTNAME", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string LASTNAME
		{
			get
			{
				return this._LASTNAME;
			}
			set
			{
				if ((this._LASTNAME != value))
				{
					this._LASTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MIDDLE NAME]", Storage="_MIDDLE_NAME", DbType="VarChar(60)")]
		public string MIDDLE_NAME
		{
			get
			{
				return this._MIDDLE_NAME;
			}
			set
			{
				if ((this._MIDDLE_NAME != value))
				{
					this._MIDDLE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR LEVEL]", Storage="_YEAR_LEVEL", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string YEAR_LEVEL
		{
			get
			{
				return this._YEAR_LEVEL;
			}
			set
			{
				if ((this._YEAR_LEVEL != value))
				{
					this._YEAR_LEVEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(20)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAM", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string PROGRAM
		{
			get
			{
				return this._PROGRAM;
			}
			set
			{
				if ((this._PROGRAM != value))
				{
					this._PROGRAM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHIFT", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SHIFT
		{
			get
			{
				return this._SHIFT;
			}
			set
			{
				if ((this._SHIFT != value))
				{
					this._SHIFT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECTION", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string SECTION
		{
			get
			{
				return this._SECTION;
			}
			set
			{
				if ((this._SECTION != value))
				{
					this._SECTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DATE ENROLLED]", Storage="_DATE_ENROLLED", DbType="Date NOT NULL")]
		public System.DateTime DATE_ENROLLED
		{
			get
			{
				return this._DATE_ENROLLED;
			}
			set
			{
				if ((this._DATE_ENROLLED != value))
				{
					this._DATE_ENROLLED = value;
				}
			}
		}
	}
	
	public partial class prof_searchResult
	{
		
		private int _PROF_ID;
		
		private string _FIRSTNAME;
		
		private string _LASTNAME;
		
		private string _MIDDLE_NAME;
		
		private string _CONTACT;
		
		private System.DateTime _BRITHDATE;
		
		private string _ADDRESS;
		
		private string _EMAIL;
		
		private System.Nullable<short> _AGE;
		
		private System.Nullable<System.DateTime> _DATE_CREATED;
		
		public prof_searchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROF_ID", DbType="Int NOT NULL")]
		public int PROF_ID
		{
			get
			{
				return this._PROF_ID;
			}
			set
			{
				if ((this._PROF_ID != value))
				{
					this._PROF_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRSTNAME", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string FIRSTNAME
		{
			get
			{
				return this._FIRSTNAME;
			}
			set
			{
				if ((this._FIRSTNAME != value))
				{
					this._FIRSTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTNAME", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string LASTNAME
		{
			get
			{
				return this._LASTNAME;
			}
			set
			{
				if ((this._LASTNAME != value))
				{
					this._LASTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MIDDLE NAME]", Storage="_MIDDLE_NAME", DbType="VarChar(60)")]
		public string MIDDLE_NAME
		{
			get
			{
				return this._MIDDLE_NAME;
			}
			set
			{
				if ((this._MIDDLE_NAME != value))
				{
					this._MIDDLE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACT", DbType="Char(11)")]
		public string CONTACT
		{
			get
			{
				return this._CONTACT;
			}
			set
			{
				if ((this._CONTACT != value))
				{
					this._CONTACT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRITHDATE", DbType="Date NOT NULL")]
		public System.DateTime BRITHDATE
		{
			get
			{
				return this._BRITHDATE;
			}
			set
			{
				if ((this._BRITHDATE != value))
				{
					this._BRITHDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this._ADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGE", DbType="SmallInt")]
		public System.Nullable<short> AGE
		{
			get
			{
				return this._AGE;
			}
			set
			{
				if ((this._AGE != value))
				{
					this._AGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_CREATED", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE_CREATED
		{
			get
			{
				return this._DATE_CREATED;
			}
			set
			{
				if ((this._DATE_CREATED != value))
				{
					this._DATE_CREATED = value;
				}
			}
		}
	}
	
	public partial class prof_viewResult
	{
		
		private int _PROF_ID;
		
		private string _FIRSTNAME;
		
		private string _LASTNAME;
		
		private string _MIDDLE_NAME;
		
		private string _CONTACT;
		
		private System.DateTime _BIRTHDATE;
		
		private string _ADDRESS;
		
		private string _EMAIL;
		
		private System.Nullable<short> _AGE;
		
		private System.Nullable<System.DateTime> _DATE_CREATED;
		
		public prof_viewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROF_ID", DbType="Int NOT NULL")]
		public int PROF_ID
		{
			get
			{
				return this._PROF_ID;
			}
			set
			{
				if ((this._PROF_ID != value))
				{
					this._PROF_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRSTNAME", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string FIRSTNAME
		{
			get
			{
				return this._FIRSTNAME;
			}
			set
			{
				if ((this._FIRSTNAME != value))
				{
					this._FIRSTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTNAME", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string LASTNAME
		{
			get
			{
				return this._LASTNAME;
			}
			set
			{
				if ((this._LASTNAME != value))
				{
					this._LASTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MIDDLE NAME]", Storage="_MIDDLE_NAME", DbType="VarChar(60)")]
		public string MIDDLE_NAME
		{
			get
			{
				return this._MIDDLE_NAME;
			}
			set
			{
				if ((this._MIDDLE_NAME != value))
				{
					this._MIDDLE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACT", DbType="Char(11)")]
		public string CONTACT
		{
			get
			{
				return this._CONTACT;
			}
			set
			{
				if ((this._CONTACT != value))
				{
					this._CONTACT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTHDATE", DbType="Date NOT NULL")]
		public System.DateTime BIRTHDATE
		{
			get
			{
				return this._BIRTHDATE;
			}
			set
			{
				if ((this._BIRTHDATE != value))
				{
					this._BIRTHDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this._ADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGE", DbType="SmallInt")]
		public System.Nullable<short> AGE
		{
			get
			{
				return this._AGE;
			}
			set
			{
				if ((this._AGE != value))
				{
					this._AGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_CREATED", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE_CREATED
		{
			get
			{
				return this._DATE_CREATED;
			}
			set
			{
				if ((this._DATE_CREATED != value))
				{
					this._DATE_CREATED = value;
				}
			}
		}
	}
	
	public partial class prog_searchResult
	{
		
		private int _PROGRAM_ID;
		
		private string _PROGRAM_DESCRIPTION;
		
		public prog_searchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAM_ID", DbType="Int NOT NULL")]
		public int PROGRAM_ID
		{
			get
			{
				return this._PROGRAM_ID;
			}
			set
			{
				if ((this._PROGRAM_ID != value))
				{
					this._PROGRAM_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAM_DESCRIPTION", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string PROGRAM_DESCRIPTION
		{
			get
			{
				return this._PROGRAM_DESCRIPTION;
			}
			set
			{
				if ((this._PROGRAM_DESCRIPTION != value))
				{
					this._PROGRAM_DESCRIPTION = value;
				}
			}
		}
	}
	
	public partial class prog_viewResult
	{
		
		private int _PROGRAM_ID;
		
		private string _PROGRAM_DESCRIPTION;
		
		public prog_viewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAM_ID", DbType="Int NOT NULL")]
		public int PROGRAM_ID
		{
			get
			{
				return this._PROGRAM_ID;
			}
			set
			{
				if ((this._PROGRAM_ID != value))
				{
					this._PROGRAM_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAM_DESCRIPTION", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string PROGRAM_DESCRIPTION
		{
			get
			{
				return this._PROGRAM_DESCRIPTION;
			}
			set
			{
				if ((this._PROGRAM_DESCRIPTION != value))
				{
					this._PROGRAM_DESCRIPTION = value;
				}
			}
		}
	}
	
	public partial class search_enrolleesResult
	{
		
		private int _STUDENT_ID;
		
		private string _FIRSTNAME;
		
		private string _LASTNAME;
		
		private string _MIDDLE_NAME;
		
		private string _YEAR_LEVEL;
		
		private string _STATUS;
		
		private string _PROGRAM;
		
		private string _SHIFT;
		
		private string _SECTION;
		
		private System.DateTime _DATE_ENROLLED;
		
		public search_enrolleesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[STUDENT ID]", Storage="_STUDENT_ID", DbType="Int NOT NULL")]
		public int STUDENT_ID
		{
			get
			{
				return this._STUDENT_ID;
			}
			set
			{
				if ((this._STUDENT_ID != value))
				{
					this._STUDENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRSTNAME", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string FIRSTNAME
		{
			get
			{
				return this._FIRSTNAME;
			}
			set
			{
				if ((this._FIRSTNAME != value))
				{
					this._FIRSTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTNAME", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string LASTNAME
		{
			get
			{
				return this._LASTNAME;
			}
			set
			{
				if ((this._LASTNAME != value))
				{
					this._LASTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MIDDLE NAME]", Storage="_MIDDLE_NAME", DbType="VarChar(60)")]
		public string MIDDLE_NAME
		{
			get
			{
				return this._MIDDLE_NAME;
			}
			set
			{
				if ((this._MIDDLE_NAME != value))
				{
					this._MIDDLE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR LEVEL]", Storage="_YEAR_LEVEL", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string YEAR_LEVEL
		{
			get
			{
				return this._YEAR_LEVEL;
			}
			set
			{
				if ((this._YEAR_LEVEL != value))
				{
					this._YEAR_LEVEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(20)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAM", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string PROGRAM
		{
			get
			{
				return this._PROGRAM;
			}
			set
			{
				if ((this._PROGRAM != value))
				{
					this._PROGRAM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHIFT", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SHIFT
		{
			get
			{
				return this._SHIFT;
			}
			set
			{
				if ((this._SHIFT != value))
				{
					this._SHIFT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECTION", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string SECTION
		{
			get
			{
				return this._SECTION;
			}
			set
			{
				if ((this._SECTION != value))
				{
					this._SECTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DATE ENROLLED]", Storage="_DATE_ENROLLED", DbType="Date NOT NULL")]
		public System.DateTime DATE_ENROLLED
		{
			get
			{
				return this._DATE_ENROLLED;
			}
			set
			{
				if ((this._DATE_ENROLLED != value))
				{
					this._DATE_ENROLLED = value;
				}
			}
		}
	}
	
	public partial class stud_searchResult
	{
		
		private string _STUD_ID;
		
		private string _FIRSTNAME;
		
		private string _LASTNAME;
		
		private string _MIDNAME;
		
		private string _GENDER;
		
		private string _CONTACT;
		
		private System.DateTime _BIRTHDATE;
		
		private short _AGE;
		
		private string _ADDRESS;
		
		private string _EMAIL;
		
		private string _YEAR_LEVEL;
		
		private string _STATUS;
		
		private System.DateTime _DATE_CREATED;
		
		private int _PROGRAM_ID;
		
		public stud_searchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_ID", DbType="VarChar(7)")]
		public string STUD_ID
		{
			get
			{
				return this._STUD_ID;
			}
			set
			{
				if ((this._STUD_ID != value))
				{
					this._STUD_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRSTNAME", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string FIRSTNAME
		{
			get
			{
				return this._FIRSTNAME;
			}
			set
			{
				if ((this._FIRSTNAME != value))
				{
					this._FIRSTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTNAME", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string LASTNAME
		{
			get
			{
				return this._LASTNAME;
			}
			set
			{
				if ((this._LASTNAME != value))
				{
					this._LASTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MIDNAME", DbType="VarChar(60)")]
		public string MIDNAME
		{
			get
			{
				return this._MIDNAME;
			}
			set
			{
				if ((this._MIDNAME != value))
				{
					this._MIDNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string GENDER
		{
			get
			{
				return this._GENDER;
			}
			set
			{
				if ((this._GENDER != value))
				{
					this._GENDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACT", DbType="Char(11)")]
		public string CONTACT
		{
			get
			{
				return this._CONTACT;
			}
			set
			{
				if ((this._CONTACT != value))
				{
					this._CONTACT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTHDATE", DbType="Date NOT NULL")]
		public System.DateTime BIRTHDATE
		{
			get
			{
				return this._BIRTHDATE;
			}
			set
			{
				if ((this._BIRTHDATE != value))
				{
					this._BIRTHDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGE", DbType="SmallInt NOT NULL")]
		public short AGE
		{
			get
			{
				return this._AGE;
			}
			set
			{
				if ((this._AGE != value))
				{
					this._AGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this._ADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR LEVEL]", Storage="_YEAR_LEVEL", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string YEAR_LEVEL
		{
			get
			{
				return this._YEAR_LEVEL;
			}
			set
			{
				if ((this._YEAR_LEVEL != value))
				{
					this._YEAR_LEVEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(20)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_CREATED", DbType="DateTime NOT NULL")]
		public System.DateTime DATE_CREATED
		{
			get
			{
				return this._DATE_CREATED;
			}
			set
			{
				if ((this._DATE_CREATED != value))
				{
					this._DATE_CREATED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAM_ID", DbType="Int NOT NULL")]
		public int PROGRAM_ID
		{
			get
			{
				return this._PROGRAM_ID;
			}
			set
			{
				if ((this._PROGRAM_ID != value))
				{
					this._PROGRAM_ID = value;
				}
			}
		}
	}
	
	public partial class stud_viewResult
	{
		
		private string _STUD_ID;
		
		private string _FIRSTNAME;
		
		private string _LASTNAME;
		
		private string _MIDNAME;
		
		private string _GENDER;
		
		private string _CONTACT;
		
		private System.DateTime _BIRTHDATE;
		
		private short _AGE;
		
		private string _ADDRESS;
		
		private string _EMAIL;
		
		private string _YEAR_LEVEL;
		
		private string _STATUS;
		
		private System.DateTime _DATE_CREATED;
		
		private int _PROGRAM_ID;
		
		public stud_viewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUD_ID", DbType="VarChar(7)")]
		public string STUD_ID
		{
			get
			{
				return this._STUD_ID;
			}
			set
			{
				if ((this._STUD_ID != value))
				{
					this._STUD_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRSTNAME", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string FIRSTNAME
		{
			get
			{
				return this._FIRSTNAME;
			}
			set
			{
				if ((this._FIRSTNAME != value))
				{
					this._FIRSTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTNAME", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string LASTNAME
		{
			get
			{
				return this._LASTNAME;
			}
			set
			{
				if ((this._LASTNAME != value))
				{
					this._LASTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MIDNAME", DbType="VarChar(60)")]
		public string MIDNAME
		{
			get
			{
				return this._MIDNAME;
			}
			set
			{
				if ((this._MIDNAME != value))
				{
					this._MIDNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string GENDER
		{
			get
			{
				return this._GENDER;
			}
			set
			{
				if ((this._GENDER != value))
				{
					this._GENDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACT", DbType="Char(11)")]
		public string CONTACT
		{
			get
			{
				return this._CONTACT;
			}
			set
			{
				if ((this._CONTACT != value))
				{
					this._CONTACT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTHDATE", DbType="Date NOT NULL")]
		public System.DateTime BIRTHDATE
		{
			get
			{
				return this._BIRTHDATE;
			}
			set
			{
				if ((this._BIRTHDATE != value))
				{
					this._BIRTHDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGE", DbType="SmallInt NOT NULL")]
		public short AGE
		{
			get
			{
				return this._AGE;
			}
			set
			{
				if ((this._AGE != value))
				{
					this._AGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this._ADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR LEVEL]", Storage="_YEAR_LEVEL", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string YEAR_LEVEL
		{
			get
			{
				return this._YEAR_LEVEL;
			}
			set
			{
				if ((this._YEAR_LEVEL != value))
				{
					this._YEAR_LEVEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(20)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_CREATED", DbType="DateTime NOT NULL")]
		public System.DateTime DATE_CREATED
		{
			get
			{
				return this._DATE_CREATED;
			}
			set
			{
				if ((this._DATE_CREATED != value))
				{
					this._DATE_CREATED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAM_ID", DbType="Int NOT NULL")]
		public int PROGRAM_ID
		{
			get
			{
				return this._PROGRAM_ID;
			}
			set
			{
				if ((this._PROGRAM_ID != value))
				{
					this._PROGRAM_ID = value;
				}
			}
		}
	}
	
	public partial class sub_searchResult
	{
		
		private string _COURSE_CODE;
		
		private string _DESCRIPTION;
		
		private string _YEAR;
		
		private string _SEMESTER;
		
		private decimal _UNIT;
		
		public sub_searchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[COURSE CODE]", Storage="_COURSE_CODE", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string COURSE_CODE
		{
			get
			{
				return this._COURSE_CODE;
			}
			set
			{
				if ((this._COURSE_CODE != value))
				{
					this._COURSE_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this._DESCRIPTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string YEAR
		{
			get
			{
				return this._YEAR;
			}
			set
			{
				if ((this._YEAR != value))
				{
					this._YEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEMESTER", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string SEMESTER
		{
			get
			{
				return this._SEMESTER;
			}
			set
			{
				if ((this._SEMESTER != value))
				{
					this._SEMESTER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT", DbType="Decimal(10,2) NOT NULL")]
		public decimal UNIT
		{
			get
			{
				return this._UNIT;
			}
			set
			{
				if ((this._UNIT != value))
				{
					this._UNIT = value;
				}
			}
		}
	}
	
	public partial class sub_viewResult
	{
		
		private string _COURSE_CODE;
		
		private string _DESCRIPTION;
		
		private string _YEAR;
		
		private string _SEMESTER;
		
		private decimal _UNIT;
		
		public sub_viewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[COURSE CODE]", Storage="_COURSE_CODE", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string COURSE_CODE
		{
			get
			{
				return this._COURSE_CODE;
			}
			set
			{
				if ((this._COURSE_CODE != value))
				{
					this._COURSE_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this._DESCRIPTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string YEAR
		{
			get
			{
				return this._YEAR;
			}
			set
			{
				if ((this._YEAR != value))
				{
					this._YEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEMESTER", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string SEMESTER
		{
			get
			{
				return this._SEMESTER;
			}
			set
			{
				if ((this._SEMESTER != value))
				{
					this._SEMESTER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT", DbType="Decimal(10,2) NOT NULL")]
		public decimal UNIT
		{
			get
			{
				return this._UNIT;
			}
			set
			{
				if ((this._UNIT != value))
				{
					this._UNIT = value;
				}
			}
		}
	}
	
	public partial class select_UserdetailResult
	{
		
		private int _id;
		
		private string _Admin_Fname;
		
		private string _Admin_Lname;
		
		private string _Admin_Midname;
		
		private string _Admin_Contact;
		
		private string _Admin_Username;
		
		private string _Admin_Pass;
		
		public select_UserdetailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Fname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Admin_Fname
		{
			get
			{
				return this._Admin_Fname;
			}
			set
			{
				if ((this._Admin_Fname != value))
				{
					this._Admin_Fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Lname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Admin_Lname
		{
			get
			{
				return this._Admin_Lname;
			}
			set
			{
				if ((this._Admin_Lname != value))
				{
					this._Admin_Lname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Midname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Admin_Midname
		{
			get
			{
				return this._Admin_Midname;
			}
			set
			{
				if ((this._Admin_Midname != value))
				{
					this._Admin_Midname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Contact", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string Admin_Contact
		{
			get
			{
				return this._Admin_Contact;
			}
			set
			{
				if ((this._Admin_Contact != value))
				{
					this._Admin_Contact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Admin_Username
		{
			get
			{
				return this._Admin_Username;
			}
			set
			{
				if ((this._Admin_Username != value))
				{
					this._Admin_Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Pass", DbType="VarChar(50)")]
		public string Admin_Pass
		{
			get
			{
				return this._Admin_Pass;
			}
			set
			{
				if ((this._Admin_Pass != value))
				{
					this._Admin_Pass = value;
				}
			}
		}
	}
	
	public partial class selectIdResult
	{
		
		private int _id;
		
		public selectIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
